application: serendipityhtc
version: 0-8
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static/images
  static_dir: static/images
  expiration: '365d'

- url: /static/images/smileys
  static_dir: static/images/smileys
  expiration: '365d'

- url: /static/
  static_dir: static
  
- url: /remote_api  
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py  
  login: admin
  
- url: /.*
  script: controller.py
